openapi: 3.0.1
info:
  title: beer-store-application API
  description: OpenAPI definition
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /orders:
    get:
      tags:
      - order
      operationId: getOrders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
      - order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /orders/{id}:
    get:
      tags:
      - order
      operationId: getOrderById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /customers/{name}:
    get:
      tags:
      - customer
      operationId: getCustomerByName
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /:
    get:
      tags:
      - home
      description: Returns a simple "Hello!"
      operationId: hello_1
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Order:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
        beers:
          type: array
          items:
            type: integer
            format: int64
    Address:
      required:
      - city
      - country
      - streetAddress
      - zip
      type: object
      properties:
        country:
          type: string
        city:
          type: string
        streetAddress:
          type: string
        zip:
          type: string
    Customer:
      required:
      - address
      - firstName
      - lastName
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
        address:
          $ref: '#/components/schemas/Address'
