-- BEER
INSERT INTO BEER (ID, BEER_STYLE, NAME) VALUES (1, 'IPA', 'Egy IPA');
INSERT INTO BEER (ID, BEER_STYLE, NAME) VALUES (2, 'APA', 'Egy APA');
INSERT INTO BEER (ID, BEER_STYLE, NAME) VALUES (3, 'ALE', 'Egy ALE');
INSERT INTO BEER (ID, BEER_STYLE, NAME) VALUES (4, 'SAISON', 'Egy SAISON');

-- CUSTOMER
INSERT INTO CUSTOMER (CITY, COUNTRY, STREET_ADDRESS, ZIP, FIRST_NAME, LAST_NAME) VALUES ('Budapest', 'Magyarország', 'Lechner Ödön fasor 9.', '1095', 'Teszt', 'Ügyfél');
INSERT INTO CUSTOMER (CITY, COUNTRY, STREET_ADDRESS, ZIP, FIRST_NAME, LAST_NAME) VALUES ('Budapest', 'Magyarország', 'Váci út 76.', '1133', 'János', 'Vitéz');
INSERT INTO CUSTOMER (CITY, COUNTRY, STREET_ADDRESS, ZIP, FIRST_NAME, LAST_NAME) VALUES ('Budapest', 'Magyarország', 'Rutafa utca 11.', '1165', 'Péter', 'Körmöczi');
INSERT INTO CUSTOMER (CITY, COUNTRY, STREET_ADDRESS, ZIP, FIRST_NAME, LAST_NAME) VALUES ('Budapest', 'Magyarország', 'Király utca 32.', '1075', 'János', 'Kiss');

-- BEER_ORDER
INSERT INTO BEER_ORDER (ID, ORDER_STATUS, CUSTOMER_ID) VALUES (1, 'NEW', 1);
INSERT INTO BEER_ORDER (ID, ORDER_STATUS, CUSTOMER_ID) VALUES (2, 'NEW', 2);

-- BEER_ORDER_BEERS
INSERT INTO BEER_ORDER_BEERS (ORDER_ID, BEERS_ID) VALUES (1, 1);
INSERT INTO BEER_ORDER_BEERS (ORDER_ID, BEERS_ID) VALUES (1, 2);
INSERT INTO BEER_ORDER_BEERS (ORDER_ID, BEERS_ID) VALUES (2, 3);
INSERT INTO BEER_ORDER_BEERS (ORDER_ID, BEERS_ID) VALUES (2, 4);

