version: '3.1'
services:
  jenkins:
    ports:
      - '8080:8080'
      - '50000:50000'
    build:
      context: ./Jenkins
      depends_on:
        - sonarqube
  sonarqube:
    ports:
      - '9000:9000'
    build:
      context: ./SonarQube
